name: lb_logger
description: Redis-based logger for Dart, named in honour of Lars Bak.
version: 0.0.2
homepage: https://github.com/evanx/lb_logger
author: Evan Summers <evan.summers@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  redis: ^0.4.5

dev_dependencies:
  test: ^0.12.0
